version: "3.8"

services:
  postgresql:
    container_name: relationspostgresql
    image: debezium/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: relationsDB
    ports:
      - "5432:5432"
  pgadmin:
    container_name: relationspgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"